import type { CatalogState } from './types/catalog';

/**
 * GENESIS_CATALOG: Expanded dummy product catalog for NoirEve.
 * Contains 40 watches across Men/Women categories for pagination testing.
 */
export const GENESIS_CATALOG: CatalogState = {
    items: [
        // === MEN'S WATCHES (24 items for 3 pages of 8) ===
        {
            id: 'submariner-001',
            brand: 'Rolex',
            model: 'Submariner Date',
            price: { amount: 14500, currency: 'USD', formatted: '$14,500' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/submariner.jpg', alt: 'Rolex Submariner', isPrimary: true }],
            description: 'The iconic divers watch, a benchmark in its category.',
            stock: 5,
        },
        {
            id: 'daytona-002',
            brand: 'Rolex',
            model: 'Cosmograph Daytona',
            price: { amount: 32000, currency: 'USD', formatted: '$32,000' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/daytona.jpg', alt: 'Rolex Daytona', isPrimary: true }],
            description: 'A watch born to race, designed for professional drivers.',
            stock: 3,
        },
        {
            id: 'nautilus-003',
            brand: 'Patek Philippe',
            model: 'Nautilus 5711/1A',
            price: { amount: 120000, currency: 'USD', formatted: '$120,000' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/nautilus.jpg', alt: 'Patek Philippe Nautilus', isPrimary: true }],
            description: 'The pinnacle of luxury sports watches.',
            stock: 2,
        },
        {
            id: 'royal-oak-004',
            brand: 'Audemars Piguet',
            model: 'Royal Oak "Jumbo"',
            price: { amount: 85000, currency: 'USD', formatted: '$85,000' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/royaloak.jpg', alt: 'Audemars Piguet Royal Oak', isPrimary: true }],
            description: 'Decidedly avant-garde and legendary.',
            stock: 4,
        },
        {
            id: 'speedmaster-005',
            brand: 'Omega',
            model: 'Speedmaster Moonwatch',
            price: { amount: 7200, currency: 'USD', formatted: '$7,200' },
            category: 'Men',
            movement: 'Manual',
            images: [{ url: '/images/watches/speedmaster.jpg', alt: 'Omega Speedmaster', isPrimary: true }],
            description: 'The first watch worn on the moon.',
            stock: 8,
        },
        {
            id: 'reverso-007',
            brand: 'Jaeger-LeCoultre',
            model: 'Reverso Duoface',
            price: { amount: 11500, currency: 'USD', formatted: '$11,500' },
            category: 'Men',
            movement: 'Manual',
            images: [{ url: '/images/watches/reverso.jpg', alt: 'JLC Reverso', isPrimary: true }],
            description: 'A classic art deco masterpiece with two faces.',
            stock: 6,
        },
        // Additional Men's Watches
        {
            id: 'casio-gshock-008',
            brand: 'Casio',
            model: 'G-Shock GA-2100',
            price: { amount: 150, currency: 'USD', formatted: '$150' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/submariner.jpg', alt: 'Casio G-Shock', isPrimary: true }],
            description: 'The iconic CasiOak, slim and stylish.',
            stock: 20,
        },
        {
            id: 'casio-edifice-009',
            brand: 'Casio',
            model: 'Edifice EQB-1100',
            price: { amount: 350, currency: 'USD', formatted: '$350' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/daytona.jpg', alt: 'Casio Edifice', isPrimary: true }],
            description: 'Bluetooth connected chronograph for the modern man.',
            stock: 15,
        },
        {
            id: 'citizen-eco-010',
            brand: 'Citizen',
            model: 'Eco-Drive Promaster',
            price: { amount: 450, currency: 'USD', formatted: '$450' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/speedmaster.jpg', alt: 'Citizen Promaster', isPrimary: true }],
            description: 'Solar powered dive watch for professionals.',
            stock: 12,
        },
        {
            id: 'citizen-attesa-011',
            brand: 'Citizen',
            model: 'Attesa AT8185',
            price: { amount: 680, currency: 'USD', formatted: '$680' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/nautilus.jpg', alt: 'Citizen Attesa', isPrimary: true }],
            description: 'Super Titanium with atomic timekeeping.',
            stock: 10,
        },
        {
            id: 'police-vertex-012',
            brand: 'Police',
            model: 'Vertex Chronograph',
            price: { amount: 280, currency: 'USD', formatted: '$280' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/royaloak.jpg', alt: 'Police Vertex', isPrimary: true }],
            description: 'Bold Italian design with multi-function dial.',
            stock: 18,
        },
        {
            id: 'police-ranger-013',
            brand: 'Police',
            model: 'Ranger PEWJG2110',
            price: { amount: 320, currency: 'USD', formatted: '$320' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/reverso.jpg', alt: 'Police Ranger', isPrimary: true }],
            description: 'Rugged design with leather strap.',
            stock: 14,
        },
        {
            id: 'leecooper-classic-014',
            brand: 'Lee Cooper',
            model: 'Classic LC06879',
            price: { amount: 120, currency: 'USD', formatted: '$120' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/submariner.jpg', alt: 'Lee Cooper Classic', isPrimary: true }],
            description: 'British heritage meets everyday elegance.',
            stock: 25,
        },
        {
            id: 'leecooper-sport-015',
            brand: 'Lee Cooper',
            model: 'Sport LC07123',
            price: { amount: 145, currency: 'USD', formatted: '$145' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/speedmaster.jpg', alt: 'Lee Cooper Sport', isPrimary: true }],
            description: 'Sporty design with stainless steel bracelet.',
            stock: 22,
        },
        {
            id: 'omega-seamaster-016',
            brand: 'Omega',
            model: 'Seamaster 300M',
            price: { amount: 5500, currency: 'USD', formatted: '$5,500' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/nautilus.jpg', alt: 'Omega Seamaster', isPrimary: true }],
            description: 'The legendary dive watch, inspired by 007.',
            stock: 7,
        },
        {
            id: 'rolex-explorer-017',
            brand: 'Rolex',
            model: 'Explorer II',
            price: { amount: 9800, currency: 'USD', formatted: '$9,800' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/daytona.jpg', alt: 'Rolex Explorer', isPrimary: true }],
            description: 'For those who explore beyond ordinary.',
            stock: 4,
        },
        {
            id: 'casio-pro-018',
            brand: 'Casio',
            model: 'Pro Trek PRW-6600',
            price: { amount: 420, currency: 'USD', formatted: '$420' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/reverso.jpg', alt: 'Casio Pro Trek', isPrimary: true }],
            description: 'Triple sensor outdoor watch for adventurers.',
            stock: 11,
        },
        {
            id: 'citizen-hawk-019',
            brand: 'Citizen',
            model: 'Nighthawk BJ7138',
            price: { amount: 520, currency: 'USD', formatted: '$520' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/royaloak.jpg', alt: 'Citizen Nighthawk', isPrimary: true }],
            description: 'Aviator watch with slide rule bezel.',
            stock: 9,
        },
        {
            id: 'police-black-020',
            brand: 'Police',
            model: 'Black Steel PEWJJ2110',
            price: { amount: 295, currency: 'USD', formatted: '$295' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/submariner.jpg', alt: 'Police Black Steel', isPrimary: true }],
            description: 'Blacked out design for the bold.',
            stock: 16,
        },
        {
            id: 'omega-planet-021',
            brand: 'Omega',
            model: 'Planet Ocean 600M',
            price: { amount: 6900, currency: 'USD', formatted: '$6,900' },
            category: 'Men',
            movement: 'Automatic',
            images: [{ url: '/images/watches/speedmaster.jpg', alt: 'Omega Planet Ocean', isPrimary: true }],
            description: 'Professional dive watch with Master Chronometer.',
            stock: 5,
        },
        {
            id: 'casio-oceanus-022',
            brand: 'Casio',
            model: 'Oceanus OCW-T200',
            price: { amount: 580, currency: 'USD', formatted: '$580' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/nautilus.jpg', alt: 'Casio Oceanus', isPrimary: true }],
            description: 'Elegant solar powered titanium watch.',
            stock: 8,
        },
        {
            id: 'citizen-corso-023',
            brand: 'Citizen',
            model: 'Corso Eco-Drive',
            price: { amount: 375, currency: 'USD', formatted: '$375' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/reverso.jpg', alt: 'Citizen Corso', isPrimary: true }],
            description: 'Sophisticated style for the modern gentleman.',
            stock: 13,
        },
        {
            id: 'leecooper-exec-024',
            brand: 'Lee Cooper',
            model: 'Executive LC08012',
            price: { amount: 165, currency: 'USD', formatted: '$165' },
            category: 'Men',
            movement: 'Quartz',
            images: [{ url: '/images/watches/daytona.jpg', alt: 'Lee Cooper Executive', isPrimary: true }],
            description: 'Dress watch with Roman numerals.',
            stock: 19,
        },

        // === WOMEN'S WATCHES (16 items for 2 pages of 8) ===
        {
            id: 'tank-006',
            brand: 'Cartier',
            model: 'Tank Louis Cartier',
            price: { amount: 12800, currency: 'USD', formatted: '$12,800' },
            category: 'Women',
            movement: 'Manual',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Cartier Tank', isPrimary: true }],
            description: 'The definitive elegance of Cartier jewelry watches.',
            stock: 3,
        },
        {
            id: 'serpenti-008',
            brand: 'Bvlgari',
            model: 'Serpenti Tubogas',
            price: { amount: 18900, currency: 'USD', formatted: '$18,900' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Bvlgari Serpenti', isPrimary: true }],
            description: 'The ultimate symbol of seduction and glamor.',
            stock: 2,
        },
        {
            id: 'citizen-fem-025',
            brand: 'Citizen',
            model: 'Silhouette Crystal',
            price: { amount: 395, currency: 'USD', formatted: '$395' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Citizen Silhouette', isPrimary: true }],
            description: 'Eco-Drive elegance with Swarovski crystals.',
            stock: 14,
        },
        {
            id: 'citizen-rose-026',
            brand: 'Citizen',
            model: 'Rose Gold EM0503',
            price: { amount: 325, currency: 'USD', formatted: '$325' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Citizen Rose Gold', isPrimary: true }],
            description: 'Romantic rose gold tone bracelet watch.',
            stock: 17,
        },
        {
            id: 'casio-baby-027',
            brand: 'Casio',
            model: 'Baby-G BGA-280',
            price: { amount: 120, currency: 'USD', formatted: '$120' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Casio Baby-G', isPrimary: true }],
            description: 'Cute, tough, and ready for anything.',
            stock: 22,
        },
        {
            id: 'casio-sheen-028',
            brand: 'Casio',
            model: 'Sheen SHE-4052',
            price: { amount: 180, currency: 'USD', formatted: '$180' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Casio Sheen', isPrimary: true }],
            description: 'Sophisticated design for professional women.',
            stock: 18,
        },
        {
            id: 'leecooper-fem-029',
            brand: 'Lee Cooper',
            model: 'Elegance LC06421',
            price: { amount: 95, currency: 'USD', formatted: '$95' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Lee Cooper Elegance', isPrimary: true }],
            description: 'Timeless British elegance for her.',
            stock: 24,
        },
        {
            id: 'leecooper-charm-030',
            brand: 'Lee Cooper',
            model: 'Charm LC07521',
            price: { amount: 110, currency: 'USD', formatted: '$110' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Lee Cooper Charm', isPrimary: true }],
            description: 'Delicate mesh bracelet with mother of pearl.',
            stock: 20,
        },
        {
            id: 'omega-aqua-031',
            brand: 'Omega',
            model: 'Aqua Terra 34mm',
            price: { amount: 6200, currency: 'USD', formatted: '$6,200' },
            category: 'Women',
            movement: 'Automatic',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Omega Aqua Terra', isPrimary: true }],
            description: 'Master Chronometer in a feminine size.',
            stock: 5,
        },
        {
            id: 'cartier-ballon-032',
            brand: 'Cartier',
            model: 'Ballon Bleu 33mm',
            price: { amount: 6950, currency: 'USD', formatted: '$6,950' },
            category: 'Women',
            movement: 'Automatic',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Cartier Ballon Bleu', isPrimary: true }],
            description: 'Floating like a balloon in the sky.',
            stock: 4,
        },
        {
            id: 'citizen-dress-033',
            brand: 'Citizen',
            model: 'Dress EM0683',
            price: { amount: 280, currency: 'USD', formatted: '$280' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Citizen Dress', isPrimary: true }],
            description: 'Perfect for special occasions.',
            stock: 16,
        },
        {
            id: 'casio-vintage-034',
            brand: 'Casio',
            model: 'Vintage LA680WA',
            price: { amount: 45, currency: 'USD', formatted: '$45' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Casio Vintage', isPrimary: true }],
            description: 'Retro digital style that never fades.',
            stock: 30,
        },
        {
            id: 'bvlgari-octo-035',
            brand: 'Bvlgari',
            model: 'Octo Finissimo',
            price: { amount: 15500, currency: 'USD', formatted: '$15,500' },
            category: 'Women',
            movement: 'Automatic',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Bvlgari Octo', isPrimary: true }],
            description: 'Ultra-thin luxury for the modern woman.',
            stock: 2,
        },
        {
            id: 'leecooper-pearl-036',
            brand: 'Lee Cooper',
            model: 'Pearl LC08821',
            price: { amount: 125, currency: 'USD', formatted: '$125' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Lee Cooper Pearl', isPrimary: true }],
            description: 'Mother of pearl dial with leather strap.',
            stock: 18,
        },
        {
            id: 'citizen-crystal-037',
            brand: 'Citizen',
            model: 'Crystal FE1230',
            price: { amount: 295, currency: 'USD', formatted: '$295' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/tank.jpg', alt: 'Citizen Crystal', isPrimary: true }],
            description: 'Sparkling crystals on rose gold tone.',
            stock: 15,
        },
        {
            id: 'casio-analog-038',
            brand: 'Casio',
            model: 'Analog LTP-E176',
            price: { amount: 85, currency: 'USD', formatted: '$85' },
            category: 'Women',
            movement: 'Quartz',
            images: [{ url: '/images/watches/serpenti.jpg', alt: 'Casio Analog', isPrimary: true }],
            description: 'Minimalist design for everyday wear.',
            stock: 28,
        },
    ],
    version: '2.0.0',
    lastUpdated: new Date().toISOString()
};
